[project]
name = "one-billion-rows-challenge"
version = "0.1.0"
description = "One billion rows challenge"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=0.20.3",
    "duckdb>=0.10.0",
    "modin[dask]>=0.27.0,<0.28.0",
    "tqdm>=4.66.3,<5.0.0"
]